# Generated by Django 4.2.6 on 2024-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_rename_user_detailsmodel_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='about',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project_brief',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project_links',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
