# Generated by Django 4.2.6 on 2024-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0004_detailsmodel_about_detailsmodel_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsmodel',
            name='about',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='project_brief',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='project_links',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='detailsmodel',
            name='skills',
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
