# Generated by Django 4.2.6 on 2024-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0005_remove_detailsmodel_about_remove_detailsmodel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=200)),
                ('project_link', models.URLField()),
                ('project_pic_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='projects',
            field=models.ManyToManyField(to='LoginUser.projects'),
        ),
    ]
