# Generated by Django 4.2.6 on 2024-01-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0006_project'),
        ('LoginUser', '0006_projects_detailsmodel_projects'),
    ]

    operations = [
    ]
