# Generated by Django 4.2.6 on 2024-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0007_merge_20240113_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsmodel',
            name='projects',
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='about_me',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project1_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project1_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project1_pic_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project1_project_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project2_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project2_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project2_pic_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project2_project_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project3_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project3_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project3_pic_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='project3_project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detailsmodel',
            name='skills',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
