# Generated by Django 4.2.6 on 2024-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0009_alter_detailsmodel_project3_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='project1_pic_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='project1_project_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='project2_pic_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='project2_project_link',
            field=models.URLField(null=True),
        ),
    ]
